package A11CollNgenerics.Lecture.Maps;

import A11CollNgenerics.Lecture.Enums.TrafficLight;

public class TestingEnums {
    public static void main(String[] args) {
        TrafficLight color = TrafficLight.GREEN;
        color = TrafficLight.YELLOW;//change bhi kr skte but limited options me se hi
        System.out.println(color);
        TrafficLight c = TrafficLight.valueOf("RED");

        Grade grade = Grade.B;
        Grade g = Grade.valueOf("C"); //another way of assigning objects of enum to reference
        Grade.values();//returns values as an array
        for (Grade value : Grade.values()) { //value is of Grade dataType(enum) that will traverse in the array generated by Grade.values()
            System.out.print(value+" ");
        }
        System.out.println();
        System.out.print("Grade is:");
        System.out.println(grade);

        switch (c) {
            case RED:
                System.out.println("Stop!");
                break;
            case GREEN:
                System.out.println("Go!");
                break;
            case YELLOW:
                System.out.println("Prepare to stop.");
                break;
        }
        

    }
}
